server:
  port: 8012

spring:
  application:
    name: miniApp
  datasource:
    url: jdbc:mysql://39.106.137.189:3306/mini_app?characterEncoding=utf-8&allowMultiQueries=true&tinyIntlisBit=false&useSSL=false
    username: root
    password: li19970712
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  elasticsearch:
    bboss:
      elasticUser: elastic
      elasticPassword: Li19970712
      elasticsearch:
        rest:
          hostNames: https://es-pje3h45r.public.tencentelasticsearch.com:9200
        dateFormat: yyyy.MM.dd
        timeZone: Asia/Shanghai
        ttl: 2d
        showTemplate: false
        discoverHost: false
      dslfile:
        refreshInterval: -1
      http:
        timeoutConnection: 5000
        timeoutSocket: 5000
        connectionRequestTimeout: 5000
        retryTime: 1
        maxLineLength: -1
        maxHeaderCount: 200
        maxTotal: 400
        defaultMaxPerRoute: 200
        soReuseAddress: false
        soKeepAlive: false
        timeToLive: 3600000
        keepAlive: 3600000
        keystore:
        keyPassword:
        hostnameVerifier:


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

imgstore:
  path: /data/store
